<?php
namespace Database\Seeders\Tables;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class QuestionsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        /**
         * Command :
         * artisan seed:generate --mode=table --tables=tags,questions,answers,question_tag
         *
         */

        $dataTables = [
            [
                'id' => 2,
                'assignment_sk' => 'Výraz \\ \\left[\\left(\\frac{2x}{x+y}-\\frac{3y}{x-y}-\\frac{2x^2-3y^2}{x^2-y^2}\\right]^{-1}:\\frac{x-y}{y}\\right]\\frac{5x}{x+y} \\ sa \\ rovná',
                'assignment_en' => 'Expression\\ \\left[\\left(\\frac{2x}{x+y}-\\frac{3y}{x-y}-\\frac{2x^2-3y^2}{x^2-y^2}\\right]^{-1}:\\frac{x-y}{y}\\right]\\frac{5x}{x+y} \\ is \\ equal \\ to',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 17:12:53',
                'updated_at' => '2025-05-11 00:48:08',
            ],
            [
                'id' => 3,
                'assignment_sk' => 'Nech \\ a\\gt0, \\ 0\\lt b\\lt \\frac{1}{2}, \\ then \\ the \\ expression \\ \\left( a+\\sqrt{a^2-\\frac{4a^2b^2}{\\left( b^2+1\\right]^2}}\\right]:\\left(\\frac{b^2+1}{2ab}\\right]^{-1} \\ is\\ equal \\ to',
                'assignment_en' => 'Let \\ a\\gt0, \\ 0\\lt b\\lt \\frac{1}{2}, \\ then \\ the \\ expression \\ \\left( a+\\sqrt{a^2-\\frac{4a^2b^2}{\\left( b^2+1\\right]^2}}\\right]:\\left(\\frac{b^2+1}{2ab}\\right]^{-1} \\ is\\ equal \\ to',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 19:11:54',
                'updated_at' => '2025-05-11 00:48:22',
            ],
            [
                'id' => 4,
                'assignment_sk' => 'Výraz\\ \\left(\\frac{a}{a+b}-\\frac{b}{b-a}-\\frac{2ab}{a^2-b^2}\\right]\\left(a-\\frac{4ab}{a+b}+b\\right]^{-1}\\ sa\\ rovná',
                'assignment_en' => 'Expression\\ \\left(\\frac{a}{a+b}-\\frac{b}{b-a}-\\frac{2ab}{a^2-b^2}\\right]\\left(a-\\frac{4ab}{a+b}+b\\right]^{-1}\\ is\\ equal\\ to',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 19:48:31',
                'updated_at' => '2025-05-11 00:48:52',
            ],
            [
                'id' => 5,
                'assignment_sk' => 'Výraz\\ \\frac{\\sqrt{a}+\\sqrt{b}+\\sqrt{a}-\\sqrt{b}}{a-b}\\cdot\\frac{a+2\\sqrt{ab}+b-2\\sqrt{ab}-2b}{a+2\\sqrt{ab}+b-a+2\\sqrt{ab}-b}\\ sa\\ rovná',
                'assignment_en' => 'Expression\\ \\frac{\\sqrt{a}+\\sqrt{b}+\\sqrt{a}-\\sqrt{b}}{a-b}\\cdot\\frac{a+2\\sqrt{ab}+b-2\\sqrt{ab}-2b}{a+2\\sqrt{ab}+b-a+2\\sqrt{ab}-b}\\ is\\ equal\\ to',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 19:56:41',
                'updated_at' => '2025-05-11 00:49:03',
            ],
            [
                'id' => 6,
                'assignment_sk' => 'Výraz\\ \\left(\\frac{x^2}{y^2}-\\frac{x}{y}\\right]\\left(\\frac{x^2+y^2}{xy}-2\\right]^{-1}\\frac{y^2}{x^2}\\left(\\frac{1}{y}-\\frac{1}{x}\\right]\\ sa\\ rovná',
                'assignment_en' => 'Expression\\ \\left(\\frac{x^2}{y^2}-\\frac{x}{y}\\right]\\left(\\frac{x^2+y^2}{xy}-2\\right]^{-1}\\frac{y^2}{x^2}\\left(\\frac{1}{y}-\\frac{1}{x}\\right]\\ is\\ equal\\ to',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 20:16:20',
                'updated_at' => '2025-05-10 20:16:20',
            ],
            [
                'id' => 7,
                'assignment_sk' => 'Kvadratický\\ trojčlen\\ 30x^2+11x-30\\ sa\\ dá\\ v\\ \\mathbb{R}\\ rozložiť\\ na\\ súčin\\ lineárnych\\ činiteľov',
                'assignment_en' => 'The\\ quadratic\\ trinomial\\ 30x^2+11x-30\\ can\\ be\\ factored\\ over\\ \\mathbb{R}\\ into\\ a\\ product\\ of\\ linear\\ factors',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 20:39:32',
                'updated_at' => '2025-05-10 22:15:56',
            ],
            [
                'id' => 8,
                'assignment_sk' => 'Mnozina\\ koreňov\\ rovnice\\ |x+2|=2|x-1|-4\\ sa\\ rovná',
                'assignment_en' => 'The\\ set\\ of\\ solutions\\ of\\ the\\ equation\\ |x+2|=2|x-1|-4\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 20:51:01',
                'updated_at' => '2025-05-10 20:51:01',
            ],
            [
                'id' => 9,
                'assignment_sk' => 'Množina\\ koreňov\\ rovnice\\ 3\\left(\\sqrt{x^2+13}-\\sqrt{x^2-11}\\right]=x\\ sa\\ rovná',
                'assignment_en' => 'The\\ set\\ of\\ solutions\\ of\\ the\\ equation\\  3\\left(\\sqrt{x^2+13}-\\sqrt{x^2-11}\\right]=x\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 20:59:06',
                'updated_at' => '2025-05-10 20:59:06',
            ],
            [
                'id' => 10,
                'assignment_sk' => 'Množina\\ koreňov\\ rovnice\\ \\frac{x-3}{x}=\\frac{p-2}{3-p} s\\ neznámou\\ x\\ a\\ parametrom\\ p\\ sa\\ rovná',
                'assignment_en' => 'The\\ set\\ of\\ solutions\\ of\\ the\\ equation\\ \\frac{x-3}{x}=\\frac{p-2}{3-p}\\ in\\ the\\ unknown\\ x\\ and\\ parameter\\ p\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 21:18:08',
                'updated_at' => '2025-05-10 21:18:08',
            ],
            [
                'id' => 11,
                'assignment_sk' => 'Riešenie\\ rovnice\\ \\frac{1}{\\sqrt{\\sqrt{x}+10}}=\\frac{1}{\\sqrt{25-2\\sqrt{x}}}\\ v\\ \\mathbb{R}\\ sa\\ rovná',
                'assignment_en' => 'The\\ solution\\ set\\ in\\ \\mathbb{R}\\ of\\ the\\ equation\\ \\frac{1}{\\sqrt{\\sqrt{x}+10}}=\\frac{1}{\\sqrt{25-2\\sqrt{x}}}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 21:27:27',
                'updated_at' => '2025-05-10 21:27:27',
            ],
            [
                'id' => 12,
                'assignment_sk' => 'Výraz\\ \\sqrt{\\frac{2x-1}{x+1}-1}\\ pre\\ x\\in \\mathbb{R}\\  má\\ zmysel\\ pre',
                'assignment_en' => 'Expression\\ \\sqrt{\\frac{2x-1}{x+1}-1}\\ for\\ x\\in \\mathbb{R}\\  is\\ defined\\ on',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 21:44:43',
                'updated_at' => '2025-05-10 21:44:43',
            ],
            [
                'id' => 13,
                'assignment_sk' => 'Riešením\\ nerovnice\\ \\sqrt{x}-3 \\le \\frac{2}{\\sqrt{x}-2}\\  v\\ \\mathbb{R}\\ je',
                'assignment_en' => 'The\\ solution\\ set\\ in\\ \\mathbb{R}\\ of\\ the\\ inequation\\ \\sqrt{x}-3 \\le \\frac{2}{\\sqrt{x}-2}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 21:54:49',
                'updated_at' => '2025-05-10 22:16:44',
            ],
            [
                'id' => 14,
                'assignment_sk' => 'Riešením\\ nerovnice\\ x-1\\lt \\sqrt{7-x}\\ v\\ \\mathbb{R}\\ je',
                'assignment_en' => 'The\\ solution\\ set\\ in\\ \\mathbb{R}\\ of\\ the\\ inequation\\ x-1\\lt \\sqrt{7-x}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 22:03:06',
                'updated_at' => '2025-05-10 22:03:06',
            ],
            [
                'id' => 15,
                'assignment_sk' => 'Riešením\\ nerovnice\\ |x+2|+1\\gt x\\ v\\ \\mathbb{R}\\ je',
                'assignment_en' => 'The\\ solution\\ set\\ in\\ \\mathbb{R}\\ of\\ the\\ inequation\\ |x+2|+1\\gt x\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 22:08:31',
                'updated_at' => '2025-05-10 22:08:31',
            ],
            [
                'id' => 16,
                'assignment_sk' => 'Riešením\\ nerovnice\\ \\sqrt{x^2}+2x^2\\le \\left(x+1\\right]^2+1\\ v\\ \\mathbb{N}\\ je',
                'assignment_en' => 'The\\ solution\\ set\\ in\\ \\mathbb{N}\\ of\\ the\\ inequation\\ \\sqrt{x^2}+2x^2\\le \\left(x+1\\right]^2+1\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 22:14:49',
                'updated_at' => '2025-05-10 22:14:49',
            ],
            [
                'id' => 17,
                'assignment_sk' => 'Objem\\ \\mathbf{V}\\ pravidelného\\ trojbokého\\ ihlana\\ s\\ dĺžkou\\ hrany\\ \\mathbf{a},\\ vyjadrený\\ ako\\ funkcia\\ jeho\\ povrchu\\ \\mathbf{S}\\ je',
                'assignment_en' => 'The\\ volume\\ \\mathbf{V}\\ of\\ a\\ regular\\ triangular\\ pyramid\\ with\\ edge\\ length\\  \\mathbf{a},\\ expressed\\ as\\ a\\ function\\ of\\ its\\ surface\\ area\\ \\mathbf{S}, is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 22:42:24',
                'updated_at' => '2025-05-10 22:42:24',
            ],
            [
                'id' => 18,
                'assignment_sk' => 'Definičný\\ obor\\ funkcie\\ f\\left(x\\right]=\\log(\\sqrt{x^2-9}-x]\\ sa\\ rovná',
                'assignment_en' => 'The\\ domain\\ of\\ the\\ function\\ f\\left(x\\right]=\\log(\\sqrt{x^2-9}-x]\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 22:52:08',
                'updated_at' => '2025-05-10 22:52:08',
            ],
            [
                'id' => 19,
                'assignment_sk' => 'Funkcia\\ f\\left(x\\right]=10^{2x-3}\\ má\\ inverznú\\ funkciu',
                'assignment_en' => 'Function\\ f\\left(x\\right]=10^{2x-3}\\ has\\ an\\ inverse function',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 23:02:03',
                'updated_at' => '2025-05-10 23:02:03',
            ],
            [
                'id' => 20,
                'assignment_sk' => 'Ak\\ f\\left(x\\right]=\\frac{1}{x-3}\\ a\\ g\\left(x\\right]=\\sqrt{2x+6}\\ potom\\ pre\\ g\\circ f\\ platí',
                'assignment_en' => 'If\\ f\\left(x\\right]=\\frac{1}{x-3}\\ and\\ g\\left(x\\right]=\\sqrt{2x+6}\\ then\\ g\\circ f\\ is\\ equal\\ to',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 23:19:44',
                'updated_at' => '2025-05-10 23:19:44',
            ],
            [
                'id' => 21,
                'assignment_sk' => 'Ak\\ \\sin{x}=-\\frac{5}{13},\\ \\pi\\lt x\\lt \\frac{3}{2}\\pi,\\  potom',
                'assignment_en' => 'if\\ \\sin{x}=-\\frac{5}{13},\\ \\pi\\lt x\\lt \\frac{3}{2}\\pi,\\  then',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 23:26:03',
                'updated_at' => '2025-05-10 23:26:03',
            ],
            [
                'id' => 22,
                'assignment_sk' => 'Rovnica\\ \\log(x+12]\\cdot log_{x}{2}=1\\ má\\ v\\ \\mathbb{R}\\ riešenie',
                'assignment_en' => 'The\\ set\\ of\\ solutions\\ of\\ the\\ equation\\ \\log(x+12]\\cdot log_{x}{2}=1\\ over\\ \\mathbb{R}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-10 23:55:41',
                'updated_at' => '2025-05-10 23:55:41',
            ],
            [
                'id' => 23,
                'assignment_sk' => 'Rovnica\\ 0.25^{2-x}=\\frac{256}{2^{x-3}}\\ má\\ riešenie\\ z\\ intervalu',
                'assignment_en' => 'The\\ solution\\ of\\ the\\ equation\\ 0.25^{2-x}=\\frac{256}{2^{x-3}}\\ lies\\ in\\ the\\ interval',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 00:04:13',
                'updated_at' => '2025-05-11 00:04:13',
            ],
            [
                'id' => 27,
                'assignment_sk' => 'Množina\\ riešení\\ rovnice\\ \\sqrt{x^{log{\\sqrt{x}}}}=10\\ v\\ \\mathbb{R}\\ je',
                'assignment_en' => 'The\\ solution\\ set\\ of\\ the\\ equation\\ \\sqrt{x^{log{\\sqrt{x}}}}=10\\ over\\ \\mathbb{R}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 00:28:48',
                'updated_at' => '2025-05-11 00:28:48',
            ],
            [
                'id' => 28,
                'assignment_sk' => 'Riešenie\\ nerovnice\\ \\frac{\\tg{x}+1}{\\tg{x}-1}\\le0\\ v\\ \\mathbb{R}\\ je',
                'assignment_en' => 'The\\ solution\\ set\\ of\\ the\\ inequation\\ \\frac{\\tg{x}+1}{\\tg{x}-1}\\le0\\ over\\ \\mathbb{R}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 00:41:15',
                'updated_at' => '2025-05-11 00:41:15',
            ],
            [
                'id' => 29,
                'assignment_sk' => 'Riešenie\\ rovnice\\ \\frac{\\cos{2x}}{cos^2{x}}=1-\\frac{2\\sin^2{x}}{\\sin(2x]}\\ v\\ \\mathbb{R}\\ je',
                'assignment_en' => 'The\\ solution\\ set\\ of\\ the\\ equation\\ \\frac{\\cos{2x}}{cos^2{x}}=1-\\frac{2\\sin^2{x}}{\\sin(2x]}\\ over\\ \\mathbb{R}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 00:47:46',
                'updated_at' => '2025-05-11 00:47:46',
            ],
            [
                'id' => 30,
                'assignment_sk' => 'Prvý\\ člen\\ a\\ diferencia\\ aritmetickej\\ postupnosti,\\ pre\\ ktorú\\ platí:\\ 3a_1-a_4=0,\\ a_5-a_2=6\\ sa\\ rovnajú',
                'assignment_en' => 'The\\ first\\ term\\ and\\ the\\ common\\ difference\\ of\\ the\\ arithmetic\\ sequence\\ satisfying:\\ 3a_1-a_4=0,\\ a_5-a_2=6\\ are',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 00:58:26',
                'updated_at' => '2025-05-11 00:58:26',
            ],
            [
                'id' => 31,
                'assignment_sk' => 'Prvý\\ člen\\ a\\ kvocient\\ geometrickej\\ postupnosti,\\ pre\\ ktorú\\ platí:\\ a_1-2a_3=9,\\ a_1\\cdot a_3=2916\\ sa\\ rovnajú',
                'assignment_en' => 'The\\ first\\ term\\ and\\ common\\ ratio\\ of\\ the\\ geometric\\ sequence\\ satisfying\\ a_1-2a_3=9,\\ a_1\\cdot a_3=2916\\ are',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 01:16:37',
                'updated_at' => '2025-05-11 01:16:37',
            ],
            [
                'id' => 32,
                'assignment_sk' => 'Veža\\ je\\ postavená\\ tak,\\ že\\ nasledújúce\\ poschodie\\ má \\frac{9}{10}\\ výšky\\ predchádzajúceho\\ poschodia.\\\\ Najmenej\\ koľko\\ poschodí\\ treba\\ vystavať,\\ aby\\ výška\\ veže\\ bola\\ väčšia\\ ako\\ 25m\\\\ ak\\ prvé\\ poschodie\\ má\\ výšku\\ 5m',
                'assignment_en' => 'A\\ tower\\ has\\ each\\ successive\\ floor\\ \\frac{9}{10}\\ the\\ height\\ of\\ its\\ predecessor.\\\\ Find\\ the\\ minimum\\ number\\ of\\ floors\\ for\\ total\\ height\\ to\\ exceed\\ 25\\ m\\ if\\ the\\ first\\ floor\\ is\\ 5\\ m\\ tall',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 01:31:47',
                'updated_at' => '2025-05-11 01:31:47',
            ],
            [
                'id' => 33,
                'assignment_sk' => 'Tri\\ prirodzené\\ čísla\\ tvoria\\ tri\\ za\\ sebou\\ idúce\\ členy\\ geometrickej\\ postupnosti.\\\\ Ich\\ súčet\\ je\\ 19\\ a\\ súčet\\ ich\\ prevrátených\\ hodnôt\\ je\\ \\frac{19}{36}.\\\\ Kvocient\\ geometrickej\\ postupnosti\\ je',
                'assignment_en' => 'Three\\ natural\\ numbers\\ form\\ three\\ consecutive\\ terms\\ of\\ a\\ geometric\\ sequence.\\\\ Their\\ sum\\ is\\ 19\\ and\\ the\\ sum\\ of\\ their\\ reciprocals\\ is\\ \\frac{19}{36}.\\\\ The\\ common\\ ratio\\ of\\ the\\ geometric\\ sequence\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 01:40:33',
                'updated_at' => '2025-05-11 01:40:33',
            ],
            [
                'id' => 34,
                'assignment_sk' => 'Nekonečný\\ rad\\ \\sum_{n=1}^\\infty \\left(\\sqrt{2}-1\\right]^n\\ má\\ súčet',
                'assignment_en' => 'The\\ infinite\\ series\\ \\sum_{n=1}^\\infty \\left(\\sqrt{2}-1\\right]^n\\ has\\ sum',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 01:48:13',
                'updated_at' => '2025-05-11 01:48:13',
            ],
            [
                'id' => 35,
                'assignment_sk' => 'Počet\\ prirodzených\\ čísel\\ menších\\ ako\\ 10^4,\\ ktorých\\ cifry\\ sú\\ navzájom\\ rôzne\\ sa\\ rovná',
                'assignment_en' => 'The\\ number\\ of\\ natural\\ numbers\\ less\\ than\\  10^4\\ whose\\ digits\\ are\\ all\\ different\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 01:55:11',
                'updated_at' => '2025-05-11 01:55:11',
            ],
            [
                'id' => 36,
                'assignment_sk' => 'Trezor\\ má\\ zámok\\ s\\ 5\\ kotúčami\\ s\\ ciframi\\ 0\\ až\\ 9.\\\\ Heslo\\ je\\ správna\\ voľba\\ cifry\\ na\\ každom\\ kotúči.\\\\ Pokladník\\ si\\ pamätá,\\ že\\ prvá\\ cifra\\ nebola\\ 0\\ ani\\ 1.\\\\ Počet\\ možností\\ je',
                'assignment_en' => 'The\\ safe\\ lock\\ has\\ 5\\ dials\\ (digits\\ 0–9].\\\\ The\\ combination\\ is\\ one\\ digit\\ per\\ dial.\\\\ The\\ cashier\\ recalls\\ the\\ first\\ digit\\ was\\ not\\ 0\\ or\\ 1.\\\\ The\\ number\\ of\\ possible\\ combinations\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 02:05:15',
                'updated_at' => '2025-05-11 02:05:15',
            ],
            [
                'id' => 37,
                'assignment_sk' => 'Trom\\ deťom\\ možno\\ rozdeliť\\ 7\\ rovnakých\\ čokolád\\ a\\ 5\\ rovnakých\\ balíčkov\\ cukríkov\\ p-spôsobmi,\\ kde\\ p\\ sa\\ rovná',
                'assignment_en' => 'The\\ number\\ of\\ ways\\ to\\ distribute\\ 7\\ identical\\ chocolates\\ and\\ 5\\ identical\\ packets\\ of\\ candies\\ to\\ three\\ children\\ is\\  p,\\\\ where\\  p\\ equals',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 02:12:17',
                'updated_at' => '2025-05-11 02:12:17',
            ],
            [
                'id' => 38,
                'assignment_sk' => 'Existujú\\ 4\\ krvné\\ skupiny\\ A, B, AB, 0.\\ Ak\\ rozdelíme\\ 10\\ osôb\\ podľa\\ uvedených\\ krvných\\ skupín,\\\\ počet\\ možných\\ rozdelení\\ sa\\ rovná',
                'assignment_en' => 'There\\ are\\ 4\\ blood\\ groups\\ A,\\ B,\\ AB,\\ 0.\\\\ If\\ we\\ assign\\ 10\\ people\\ to\\ these\\ groups,\\\\ the\\ number\\ of\\ possible\\ distributions\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 02:16:13',
                'updated_at' => '2025-05-11 02:16:13',
            ],
            [
                'id' => 39,
                'assignment_sk' => 'Na\\ poličke\\ v\\ kníhkupectve\\ je\\ 5\\ rovnakých\\ slovenských,\\ 3\\ rovnaké\\ nemecké\\ a\\ 2\\ rovnaké\\ anglické\\ knihy.\\\\ počet\\ spôsobov,\\ ktorými\\ možno\\ knihy\\ na\\ poličke\\ zoradiť\\ sa\\ rovná',
                'assignment_en' => 'On\\ a\\ bookstore\\ shelf\\ are\\ 5\\ identical\\ Slovak,\\ 3\\ identical\\ German,\\ and\\ 2\\ identical\\ English\\ books.\\\\ The\\ number\\ of\\ ways\\ to\\ arrange\\ the\\ books\\ on\\ the\\ shelf\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 02:20:48',
                'updated_at' => '2025-05-11 02:20:48',
            ],
            [
                'id' => 40,
                'assignment_sk' => 'Na\\ kruhovom\\ ciferníku\\ hodín\\ zviera\\ priamka\\ spájajúca\\ cifry\\ 1\\ a\\ 6\\ s\\ priamkou\\ spájajúcou\\ cifry\\ 2\\ a\\ 9\\ uhol',
                'assignment_en' => 'On\\ a\\ circular\\ clock\\ face,\\ the\\ line\\ joining\\ the\\ numerals\\ 1\\ and\\ 6\\\\ makes\\ an\\ angle\\ with\\ the\\ line\\ joining\\ the\\ numerals\\ 2\\ and\\ 9.',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 02:28:20',
                'updated_at' => '2025-05-11 02:28:20',
            ],
            [
                'id' => 41,
                'assignment_sk' => 'Z\\ vrcholu\\ budovy,\\ ktorá\\ má\\ výšku\\ \\sqrt{3}\\cdot 10\\  metrov\\\\ a\\ od\\ cesty\\ je\\ vzdialená\\ 10\\ metrov\\ vidieť\\ šírku\\ cesty\\ pod\\ uhlom\\ 15^\\circ.\\ Cesta\\ má\\ šírku',
                'assignment_en' => 'From\\ the\\ top\\ of\\ a\\ building\\ of\\ height\\ \\sqrt{3}\\cdot 10\\ meters,\\\\ located\\ 10\\ meters\\ from\\ the\\ road,\\ the\\ width\\ of\\ the\\ road\\ is\\ seen\\ under\\ an\\ angle\\ of\\ 15^\\circ.\\\\ The\\ width\\ of\\ the\\ road\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 02:35:22',
                'updated_at' => '2025-05-11 02:35:22',
            ],
            [
                'id' => 42,
                'assignment_sk' => 'Trojuholník\\ má\\ plošný\\ obsah\\ P=3+\\sqrt{3}\\ a\\ jeho\\ uhly\\ sú\\ \\alpha=45^\\circ,\\ \\beta=60^\\circ.\\\\ Dĺžky\\ strán\\ trojuholníka\\ sa\\ rovnajú',
                'assignment_en' => 'The\\ triangle\\ has\\ area\\ P=3+\\sqrt{3}\\ and\\ its\\ angles\\ are\\ \\alpha=45^\\circ,\\ \\beta=60^\\circ.\\\\ The\\ side\\ lengths\\ of\\ the\\ triangle\\ are',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 02:41:52',
                'updated_at' => '2025-05-11 02:41:52',
            ],
            [
                'id' => 43,
                'assignment_sk' => 'V\\ pravouhlom\\ trjuholníku\\ ABC\\ sú\\ dve\\ odevsny\\ a=15,\\ b=20.\\\\ Polomer\\ opísnej\\ kružnice\\ r\\\\a\\ vpísnej\\ kružnice\\ p\\ sa\\ rovnajú',
                'assignment_en' => 'In\\ the\\ right\\ triangle\\ ABC,\\ the\\ legs\\ are\\ a=15,\\ b=20.\\\\ The\\ radius\\ of\\ the\\ circumscribed\\ circle\\ r\\ and\\ the\\ radius\\ of\\ the\\ inscribed\\ circle\\ p\\ are',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 02:46:54',
                'updated_at' => '2025-05-11 02:46:54',
            ],
            [
                'id' => 44,
                'assignment_sk' => 'Trojuholník\\ ABC\\ so\\ stranou\\ c=6\\ a\\ \\alpha:\\beta:\\gamma=1:1:4\\ má\\ plošný\\ obsah',
                'assignment_en' => 'Triangle\\ ABC\\ with\\ side\\ c=6\\ and\\ \\alpha:\\beta:\\gamma=1:1:4\\ has\\ area',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 02:50:11',
                'updated_at' => '2025-05-11 02:50:11',
            ],
            [
                'id' => 45,
                'assignment_sk' => 'Nech\\ A\'=\\left(2,\\ 1\\right],\\ B\'=\\left(5,\\ 3\\right],\\ C\'=\\left(3,\\ -4\\right],\\\\  sú\\ stredy\\ protiľahlých\\ strán\\ trojuholníka\\ ABC.\\ Potom\\ vrcholy\\ A, B, C\\ majú\\ súradnice',
                'assignment_en' => 'Let\\ A\'=(2,\\ 1],\\ B\'=(5,\\ 3],\\ C\'=(3,\\ -4]\\ be\\ the\\ midpoints\\ of\\ the\\ opposite\\ sides\\ of\\ triangle\\ ABC.\\\\ Then\\ the\\ vertices\\ A,\\ B,\\ C\\ have\\ coordinates',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 03:03:24',
                'updated_at' => '2025-05-11 03:03:24',
            ],
            [
                'id' => 46,
                'assignment_sk' => 'Rovnica\\ kružnice\\ prechádzajúcej\\ bodmi\\ A=\\left(1,\\ 1\\right],\\ B=\\left(1,\\ -1\\right],\\ A=\\left(2,\\ 0\\right]\\ je',
                'assignment_en' => 'The\\ equation\\ of\\ the\\ circle\\ passing\\ through\\ points\\ A=(1,\\ 1],\\ B=(1,\\ -1],\\ C=(2,\\ 0]\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 03:08:13',
                'updated_at' => '2025-05-11 03:08:13',
            ],
            [
                'id' => 47,
                'assignment_sk' => 'Rovnica\\ hyperboly\\ so\\ stredom\\ v\\ začiatku,\\ s\\ ohniskami\\ na\\ osi\\ o_y,\\ na\\ ktorej\\ leží\\ bod\\ M=\\left(-1,\\ \\frac{9}{2} \\right]\\ a\\ ktorej\\ asymptoty\\ majú\\ rovnice\\ y=\\pm\\frac{3}{2}x\\  je',
                'assignment_en' => 'The\\ equation\\ of\\ the\\ hyperbola\\ with\\ center\\ at\\ the\\ origin,\\ foci\\ on\\ the\\ y-axis,\\ passing\\ through\\ M=\\left(-1,\\frac{9}{2}\\right],\\ and\\ with\\ asymptotes\\ y=\\pm\\frac{3}{2}x,\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 03:17:50',
                'updated_at' => '2025-05-11 03:17:50',
            ],
            [
                'id' => 48,
                'assignment_sk' => 'Parabola\\ prechádzajúca\\ podom\\ A=\\left(-5,\\ 4\\right]\\ má\\ dotyčnicu\\ s\\ rovinicou\\ y-3=0\\ vo\\ svojom\\ vrchole.\\\\ Jej\\ os\\ má\\ rovnicu\\ x+7=0.\\ Rovnica\\ paraboly\\ je',
                'assignment_en' => 'The\\ parabola\\ passing\\ through\\ A=\\left(-5,\\ 4\\right]\\ has\\ the\\ tangent\\ line\\ y-3=0\\ at\\ its\\ vertex.\\\\ Its\\ axis\\ is\\ x+7=0.\\ The\\ equation\\ of\\ the\\ parabola\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 03:24:48',
                'updated_at' => '2025-05-11 03:24:48',
            ],
            [
                'id' => 49,
                'assignment_sk' => 'Bod\\ M=\\left(3,\\ -1\\right]\\ je\\ koncový\\ bod\\ vedľajšej\\ osi\\ elipsy.\\\\ Ohniská\\ elipsy\\ ležia\\ na\\ priamke\\ p:y+6=0.\\\\ Pre\\ jej\\ excentricitu\\ a\\ dĺžku\\ hlavnej\\ polosi\\ platí\\ \\frac{e}{a}=\\frac{\\sqrt{2}}{2}.\\\\ Elipsa\\ má\\ rovnicu',
                'assignment_en' => 'Point\\ M=\\left(3,\\,-1\\right]\\ is\\ a\\ minor-axis\\ endpoint.\\\\ The\\ foci\\ lie\\ on\\ the\\ line\\ p:\\ y+6=0.\\\\ For\\ its\\ eccentricity\\ and\\ semi-major\\ axis\\ length\\ we\\ have\\ \\frac{e}{a}=\\frac{\\sqrt{2}}{2}.\\\\ The\\ equation\\ of\\ the\\ ellipse\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 03:35:55',
                'updated_at' => '2025-05-11 03:35:55',
            ],
            [
                'id' => 50,
                'assignment_sk' => 'Objem\\ zrezaného\\ kužela,\\\\ ktorého\\ podstavy\\ sú\\ kruhy\\ opísané\\ a\\ vpísané\\ dvom\\ rovnomežným\\ stenám\\ kocky\\ s\\ dĺžkou\\ hrany\\ \\mathbf{a}\\\\ sa\\ rovná',
                'assignment_en' => 'The\\ volume\\ of\\ the\\ truncated\\ cone,\\\\ whose\\ bases\\ are\\ the\\ circles\\ circumscribed\\ about\\ and\\ inscribed\\ in\\ two\\ opposite\\ faces\\ of\\ a\\ cube\\ of\\ edge\\ length\\ \\mathbf{a},\\\\ is\\ equal\\ to',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 03:44:34',
                'updated_at' => '2025-05-11 03:44:34',
            ],
            [
                'id' => 51,
                'assignment_sk' => 'Rovnica\\ roviny\\ \\alpha,\\ ktorá\\ obsahuje\\ bod\\ A=\\left[2,\\ -1,\\ -4\\right]\\ a\\ je\\ kolmá\\ na\\ priamku\\ p: \\left[x,\\ y,\\ z\\right]=\\left[3-2t,\\ t,\\ 7\\right]\\ je',
                'assignment_en' => 'The\\ equation\\ of\\ the\\ plane\\ \\alpha\\ containing\\ the\\ point\\ A=\\left[2,\\ -1,\\ -4\\right]\\ and\\ perpendicular\\ to\\ the\\ line\\ p:\\ \\left[x,\\ y,\\ z\\right]=\\left[3-2t,\\ t,\\ 7\\right]\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 03:50:08',
                'updated_at' => '2025-05-11 03:50:08',
            ],
            [
                'id' => 52,
                'assignment_sk' => 'Rovnica\\ priamky\\ p,\\ ktorá\\ prechádza\\ bodom\\ P=\\left[-5,\\ 1,\\ 0\\right]\\ a\\ je\\ kolmá\\ na\\ priamku\\ q:\\left[x,\\ y,\\ z\\right]=\\left[3t,\\ 1-2t,\\ -4+t\\right],\\ s\\ ktorou\\ je\\ rôznobežná\\ sa\\ rovná',
                'assignment_en' => 'The\\ equation\\ of\\ the\\ line\\ p,\\ which\\ passes\\ through\\ the\\ point\\ P=\\left[-5,\\ 1,\\ 0\\right]\\ and\\ is\\ perpendicular\\ to\\ the\\ line\\ q:\\ \\left[x,\\ y,\\ z\\right]=\\left[3t,\\ 1-2t,\\ -4+t\\right],\\ skew\\ to\\ it,\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 03:57:22',
                'updated_at' => '2025-05-11 03:57:22',
            ],
            [
                'id' => 53,
                'assignment_sk' => 'Guľová\\ plocha\\ s\\ polomerom\\ 4,\\\\ ktorej\\ stred\\ leží\\ na\\ priamke\\ s:\\left[x,\\ y,\\ z\\right]=\\left[-2+3t,\\ 8+4t,\\ 6-5t\\right],\\ t\\in \\mathbb{R}\\ sa\\ dotýka\\ roviny\\ y=0.\\\\ Jej\\ rovnica\\ je',
                'assignment_en' => 'The\\ sphere\\ of\\ radius\\ 4,\\\\ whose\\ center\\ lies\\ on\\ the\\ line\\ s:\\ \\left[x,\\ y,\\ z\\right]=\\left[-2+3t,\\ 8+4t,\\ 6-5t\\right],\\ t\\in\\mathbb{R},\\ and\\ tangent\\ to\\ the\\ plane\\ y=0,\\\\has\\ equation',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 04:08:11',
                'updated_at' => '2025-05-11 04:08:11',
            ],
            [
                'id' => 55,
                'assignment_sk' => 'Rovnica\\ dotykovej\\ roviny\\ ku\\ guľovej\\ ploche\\ (x+1]^2+(y-4]^2+(z-2]^2=25,\\ ktorá\\ je\\ rovnobežná\\ s\\ rovinou\\ \\alpha:x-8y-4z+7=0\\ sa\\ rovná',
                'assignment_en' => 'The\\ equation\\ of\\ the\\ tangent\\ plane\\ to\\ the\\ sphere\\ (x+1]^2+(y-4]^2+(z-2]^2=25,\\ parallel\\ to\\ the\\ plane\\ \\alpha:x-8y-4z+7=0,\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 04:14:45',
                'updated_at' => '2025-05-11 04:14:45',
            ],
            [
                'id' => 56,
                'assignment_sk' => 'Je\\ daná\\ lineárna\\ funkcia\\ f(x]=2x+4.\\ Nájdite\\ jej\\ nulové\\ body',
                'assignment_en' => 'The\\ linear\\ function\\ f(x]=2x+4\\ is\\ given.\\ Find\\ it\'s\\ zeros',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 13:27:52',
                'updated_at' => '2025-05-11 13:27:52',
            ],
            [
                'id' => 57,
                'assignment_sk' => 'Uvažujme\\ dva\\ sústredné\\ kruhy\\ s\\ polomermi\\ r_1\\ a\\ r_2.\\\\ Vyberte\\ veľkosti\\ polomerov\\ tak,\\ aby\\ veľkosť\\ plochy\\ medzikružia\\ bola\\ 3\\pi',
                'assignment_en' => 'Consider\\ two\\ concentric\\ circles\\ with\\ radii\\  r_1​ \\ and\\  r_2.\\\\ Choose\\ values\\ of\\ the\\ radii\\ so\\ that\\ the\\ area\\ of\\ the\\ annulus\\ is\\ 3\\pi',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 13:34:41',
                'updated_at' => '2025-05-11 13:34:41',
            ],
            [
                'id' => 58,
                'assignment_sk' => 'Rovnica\\ 2^x+\\frac{1}{2^x}=2',
                'assignment_en' => 'Equation\\ 2^x+\\frac{1}{2^x}=2',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 13:41:35',
                'updated_at' => '2025-05-11 13:41:35',
            ],
            [
                'id' => 59,
                'assignment_sk' => 'Nájdite\\ súčet\\ prvých\\ piatich\\ členov\\ a_1+a_2+a_3+a_4+a_5\\ aritmetickej\\ postupnosti\\ \\{a_n\\}_{n=1}^\\infty ,\\\\ ak\\ viete,\\ že\\ a_2+a_3+a_4=9',
                'assignment_en' => 'Find\\ the\\ sum\\ of\\ the\\ first\\ five\\ terms\\ a_1+a_2+a_3+a_4+a_5\\ of\\ an\\ arithmetic\\ progression,\\\\ given\\ that\\ a_2+a_3+a_4=9',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 13:50:09',
                'updated_at' => '2025-05-11 13:50:09',
            ],
            [
                'id' => 60,
                'assignment_sk' => 'Kvadratická\\ rovnica\\ 3x^2+2x-3=0\\ má:',
                'assignment_en' => 'Quadratic\\ equation\\ 3x^2+2x-3=0\\ has:',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 13:56:17',
                'updated_at' => '2025-05-11 13:56:17',
            ],
            [
                'id' => 61,
                'assignment_sk' => 'Výraz\\ \\frac{a^2-2ab+b^2}{a^3-a^2b-ab^2+b^3}\\  sa\\ pre\\ a\\ne b\\ a\\ a\\ne -b\\  rovná\\ výrazu',
                'assignment_en' => 'The\\ expression\\ \\frac{a^2 - 2ab + b^2}{a^3 - a^2b - ab^2 + b^3},\\ for\\ a \\neq b\\ and\\ a \\neq -b,\\ equals\\ the\\ expression',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 14:47:54',
                'updated_at' => '2025-05-11 14:47:54',
            ],
            [
                'id' => 62,
                'assignment_sk' => 'Rovnica\\ \\sqrt{1+x-2x^2}=\\sqrt{x}\\ (v\\ \\mathbb{R}]',
                'assignment_en' => 'Equation\\ \\sqrt{1+x-2x^2}=\\sqrt{x}\\ (over\\ \\mathbb{R}]',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 14:55:23',
                'updated_at' => '2025-05-11 14:55:23',
            ],
            [
                'id' => 63,
                'assignment_sk' => 'Dížky\\ uhlopriečok\\ kosoštvorca\\ sú\\ 6\\ a\\ 8\\ cm.\\ Jeho\\ obvod',
                'assignment_en' => 'The\\ lengths\\ of\\ the\\ diagonals\\ of\\ a\\ rhombus\\ are\\ 6\\ cm\\ and\\ 8\\ cm.\\\\ Its\\ perimeter\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 14:59:40',
                'updated_at' => '2025-05-11 14:59:40',
            ],
            [
                'id' => 64,
                'assignment_sk' => 'Koľko\\ je\\ štvorciferných\\ čísel,\\ ktoré\\ majú\\ vo\\ svojom\\ zápise\\ všetky\\ cifry\\ rôzne',
                'assignment_en' => 'How\\ many\\ four-digit\\ numbers\\ have\\ all\\ digits\\ different?',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 15:03:54',
                'updated_at' => '2025-05-11 15:03:54',
            ],
            [
                'id' => 65,
                'assignment_sk' => 'Nájdite\\ počet\\ priesečníkov\\ grafu\\ funkcie\\ f(x]=x^2-2x+2\\ a\\ priamky\\ y=1',
                'assignment_en' => 'Find\\ the\\ number\\ of\\ intersections\\ of\\ the\\ graph\\ of\\ the\\ function\\ f(x]=x^2-2x+2\\ and\\ the\\ line\\ y=1',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 15:08:17',
                'updated_at' => '2025-05-11 15:08:17',
            ],
            [
                'id' => 66,
                'assignment_sk' => 'Množina\\ všetkých\\ riešení\\ rovnice\\ \\sin{x}=\\cos{x}\\ je',
                'assignment_en' => 'The\\ set\\ of\\ all\\ solutions\\ of\\ the\\ equation\\ \\sin{x} = \\cos{x}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 19:28:31',
                'updated_at' => '2025-05-11 19:28:31',
            ],
            [
                'id' => 67,
                'assignment_sk' => 'Spoločný\\ menovateľ\\ zlomkov\\ \\frac{x+1}{x-1},\\frac{x-1}{x+1},\\frac{x}{1+x^2}\\ je',
                'assignment_en' => 'The\\ common\\ denominator\\ of\\ the\\ fractions\\ \\frac{x+1}{x-1},\\ \\frac{x-1}{x+1},\\ \\frac{x}{1+x^2}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 19:32:42',
                'updated_at' => '2025-05-11 19:32:42',
            ],
            [
                'id' => 68,
                'assignment_sk' => 'ak\\ \\log{3}=a\\\\ a \\ \\log{2=b},\\ čomu\\ sa\\ rovná\\ \\log{12}',
                'assignment_en' => 'If\\ \\log{3}=a\\ and\\ \\log{2}=b,\\ then\\ \\log{12}\\ equals',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 19:35:43',
                'updated_at' => '2025-05-11 19:35:43',
            ],
            [
                'id' => 69,
                'assignment_sk' => 'Každý\\ prvok\\ množiny\\ M\\ je\\ prirodzené\\ číslo,\\ ktoré\\ je\\ deliteľné\\ práve\\ dvoma\\ číslami\\ z\\ trojice\\ čísel\\ 3, 11, 33.\\\\ Vyberte\\ množinu\\ s\\ touto\\ vlastnosťou',
                'assignment_en' => 'Each\\ element\\ of\\ the\\ set\\ M\\ is\\ a\\ natural\\ number\\ divisible\\ by\\ exactly\\ two\\ of\\ the\\ numbers\\ 3,\\ 11,\\ 33.\\\\ Select\\ the\\ set\\ with\\ this\\ property.',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 19:39:49',
                'updated_at' => '2025-05-11 19:39:49',
            ],
            [
                'id' => 70,
                'assignment_sk' => 'Riešte\\ nerovnicu\\ |\\frac{x-3}{2x-5}|\\ge 1.\\\\ Množina\\ všetkých\\ jej\\ riešení\\ je',
                'assignment_en' => 'Solve\\ the\\ inequality\\ \\left|\\frac{x-3}{2x-5}\\right|\\ge 1.\\\\ The\\ set\\ of\\ all\\ its\\ solutions\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 19:44:55',
                'updated_at' => '2025-05-11 19:44:55',
            ],
            [
                'id' => 71,
                'assignment_sk' => 'O\\ trojuholníku\\ ABC\\ je\\ vyslovený\\ výrok:\\\\ \\mathit{"Ak\\ má\\ trojuholník\\ ABC\\ zhodné\\ uhly\\ pri\\ vrcholoch\\ A\\ a\\ B,\\ tak\\ je\\ rovnostranný."}\\\\ Negáciou\\ tohto\\ výroku\\ je\\ výrok:',
                'assignment_en' => 'Regarding\\ triangle\\ ABC,\\ the\\ statement\\ is:\\ “If\\ triangle\\ ABC\\ has\\ equal\\ angles\\ at\\ vertices\\ A\\ and\\ B,\\ then\\ it\\ is\\ equilateral.”\\\\ The\\ negation\\ of\\ this\\ statement\\ is:',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 19:55:14',
                'updated_at' => '2025-05-11 19:55:14',
            ],
            [
                'id' => 72,
                'assignment_sk' => 'Je\\ daná\\ lineárna\\ funkcia\\ f(x]=3x-1.\\ Nájdite\\ jej\\ nulové\\ body.',
                'assignment_en' => 'The\\ linear\\ function\\ f(x]=3x-1\\ is\\ given.\\ Find\\ its\\ zeros.',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 19:58:41',
                'updated_at' => '2025-05-11 19:58:41',
            ],
            [
                'id' => 73,
                'assignment_sk' => 'Kvadratická\\ rovnica\\ 2x^2 + x - 5 = 0\\ má:',
                'assignment_en' => 'The\\ quadratic\\ equation\\ 2x^2 + x - 5 = 0\\ has:',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:02:54',
                'updated_at' => '2025-05-11 20:02:54',
            ],
            [
                'id' => 74,
                'assignment_sk' => 'Rovnica\\ \\sqrt{-x^2 - 2x - 9}\\ =\\ \\sqrt{4x}\\ (\\ v\\ \\mathbb{R}]',
                'assignment_en' => 'The\\ equation\\ \\sqrt{-x^2 - 2x - 9}\\ =\\ \\sqrt{4x}\\ (over\\ \\mathbb{R}]',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:09:45',
                'updated_at' => '2025-05-11 20:09:45',
            ],
            [
                'id' => 75,
                'assignment_sk' => 'Riešte\\ nerovnicu\\ \\frac{2x^2 - 3x + 5}{x+1}\\ge\\ 2.\\\\ Množina\\ všetkých\\ jej\\ riešení\\ je',
                'assignment_en' => 'Solve\\ the\\ inequality\\ \\frac{2x^2 - 3x + 5}{x+1}\\ge\\ 2.\\\\ The\\ set\\ of\\ all\\ its\\ solutions\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:14:42',
                'updated_at' => '2025-05-11 20:14:42',
            ],
            [
                'id' => 76,
                'assignment_sk' => 'M\\ je\\ množina\\ všetkých\\ dvojciferných\\ prirodzených\\ čísel,\\\\ ktoré\\ sú\\ deliteľné\\ štyrmi\\ a\\ šiestimi,\\ a\\ nie\\ sú\\ deliteľné\\ ôsmimi.\\\\ Vyberte\\ množinu\\ M.',
                'assignment_en' => 'M\\ is\\ the\\ set\\ of\\ all\\ two-digit\\ natural\\ numbers\\ that\\ are\\ divisible\\ by\\ 4\\ and\\ 6,\\\\ but\\ not\\ by\\ 8.\\ Select\\ the\\ set\\ M.',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:18:11',
                'updated_at' => '2025-05-11 20:18:11',
            ],
            [
                'id' => 77,
                'assignment_sk' => 'Koľko\\ je\\ štvorciferných\\ čísel,\\\\ ktoré\\ majú\\ vo\\ svojom\\ zápise\\ dve\\ párne\\ a\\ dve\\ nepárne\\ cifry?\\\\ (Nulu\\ považujte\\ za\\ párnu\\ cifru.]',
                'assignment_en' => 'How\\ many\\ four-digit\\ numbers\\ have\\ exactly\\ two\\ even\\ digits\\\\ and\\ two\\ odd\\ digits\\ in\\ their\\ representation?\\ (Treat\\ zero\\ as\\ an\\ even\\ digit.]',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:21:00',
                'updated_at' => '2025-05-11 20:21:00',
            ],
            [
                'id' => 78,
                'assignment_sk' => 'Ak\\ \\log{3}=a\\ a\\ \\log{4}=b,\\ čomu\\ sa\\ rovná\\ \\log{6}?',
                'assignment_en' => 'If\\ \\log{3}=a\\ and\\ \\log{4}=b,\\ what\\ is\\ \\log{6}?',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:22:32',
                'updated_at' => '2025-05-11 20:22:32',
            ],
            [
                'id' => 79,
                'assignment_sk' => 'Nájdite\\ stý\\ člen\\ a_{100}\\ aritmetickej\\ postupnosti\\ \\{a_n\\}_{n=1}^\\infty,\\ ak\\ a_{n+1}=a_{n}-\\frac{1}{3},\\ a_1=65.',
                'assignment_en' => 'Find\\ the\\ 100th\\ term\\ a_{100}\\ of\\ the\\ arithmetic\\ progression\\ \\{a_n\\}_{n=1}^\\infty,\\ given\\ that\\ a_{n+1}=a_n-\\frac{1}{3},\\ a_1=65.',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:26:07',
                'updated_at' => '2025-05-11 20:26:07',
            ],
            [
                'id' => 80,
                'assignment_sk' => 'V\\ rovine\\ leží\\ priamka\\ p\\ a\\ bod\\ A.\\\\ Vzdialenosť\\ bodu\\ A\\ od\\ priamky\\ p\\ je\\ 1.\\\\ Na\\ priamke\\ p\\ ležia\\ body\\ B\\ a\\ C.\\ Trojuholník\\ ABC\\ je\\ rovnostranný.\\\\ Aká\\ je\\ dĺžka\\ strany\\ BC',
                'assignment_en' => 'In\\ the\\ plane\\ lies\\ a\\ line\\ p\\ and\\ a\\ point\\ A.\\\\ The\\ distance\\ from\\ A\\ to\\ p\\ is\\ 1.\\\\ Points\\ B\\ and\\ C\\ lie\\ on\\ p.\\ Triangle\\ ABC\\ is\\ equilateral.\\\\ What\\ is\\ the\\ length\\ of\\ side\\ BC',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:29:18',
                'updated_at' => '2025-05-11 20:29:18',
            ],
            [
                'id' => 81,
                'assignment_sk' => 'Rovnica\\ 4^x-2^x=2',
                'assignment_en' => 'Equation\\ 4^x-2^x=2',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:32:18',
                'updated_at' => '2025-05-11 20:32:18',
            ],
            [
                'id' => 82,
                'assignment_sk' => 'Výraz\\ \\frac{1-\\sqrt{a}}{1+\\sqrt{a}}:\\frac{1-a}{1+a}\\ sa\\ pre\\ a\\ge0,\\ a\\ne1\\ rovná\\ výrazu',
                'assignment_en' => 'The\\ expression\\ \\frac{1-\\sqrt{a}}{1+\\sqrt{a}}\\colon\\frac{1-a}{1+a}\\ for\\ a\\ge0,\\ a\\ne1\\ equals\\ the\\ expression',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:36:54',
                'updated_at' => '2025-05-11 20:36:54',
            ],
            [
                'id' => 83,
                'assignment_sk' => 'Spoločný\\ menovateľ\\ zlomkov\\ \\frac{x}{x+1},\\ \\frac{x}{x-2},\\ \\frac{x}{2+x-x^2}\\ je',
                'assignment_en' => 'The\\ common\\ denominator\\ of\\ the\\ fractions\\ \\frac{x}{x+1},\\ \\frac{x}{x-2},\\ \\frac{x}{2 + x - x^2}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:39:29',
                'updated_at' => '2025-05-11 20:39:29',
            ],
            [
                'id' => 84,
                'assignment_sk' => 'Nájdite\\ počet\\ priesečníkov\\ grafu\\ funkcie\\ f(x]=x^2-3x+4\\ a\\ priamky\\ y=x',
                'assignment_en' => 'Find\\ the\\ number\\ of\\ intersections\\ of\\ the\\ graph\\ of\\ the\\ function\\\\ f(x]=x^2-3x+4\\ and\\ the\\ line\\ y=x',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:43:33',
                'updated_at' => '2025-05-11 20:43:33',
            ],
            [
                'id' => 85,
                'assignment_sk' => 'Množina\\ všetkých\\ riešení\\ rovnice\\ \\tan x = \\cot x\\ je',
                'assignment_en' => 'The\\ set\\ of\\ all\\ solutions\\ of\\ the\\ equation\\ \\tan x = \\cot x\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:45:18',
                'updated_at' => '2025-05-11 20:45:18',
            ],
            [
                'id' => 86,
                'assignment_sk' => 'Množina\\ všetkých\\ riešení\\ rovnice\\ \\sin x=\\sqrt{3}\\cos{x}\\ je',
                'assignment_en' => 'The\\ set\\ of\\ all\\ solutions\\ of\\ the\\ equation\\ \\sin x=\\sqrt{3}\\cos{x}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 20:58:24',
                'updated_at' => '2025-05-11 20:58:24',
            ],
            [
                'id' => 87,
                'assignment_sk' => 'Kvadratická\\ rovnica\\ 2x^2 + 7x - 4 = 0\\ má:',
                'assignment_en' => 'The\\ quadratic\\ equation\\ 2x^2 + 7x - 4 = 0\\ has:',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:01:18',
                'updated_at' => '2025-05-11 21:01:18',
            ],
            [
                'id' => 88,
                'assignment_sk' => 'Zámok\\ s\\ číselníkom\\ má\\ trojciferný\\ kód\\ A B C.\\\\ Každá\\ cifra\\ je\\ z\\ množiny\\ \\{0,1,2,3,4,5,6,7,8,9\\}.\\\\ Koľko\\ je\\ rôznych\\ kódov,\\ ak\\ kód\\ má\\ najviac\\ dve\\ cifry\\ rovnaké?',
                'assignment_en' => 'A\\ lock\\ with\\ a\\ numeric\\ dial\\ uses\\ a\\ three-digit\\ code\\ ABC.\\\\ Each\\ digit\\ is\\ from\\ the\\ set\\ \\{0,1,2,3,4,5,6,7,8,9\\}.\\\\ How\\ many\\ different\\ codes\\ are\\ there\\ if\\ the\\ code\\ has\\ at\\ most\\ two\\ identical\\ digits?',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:05:29',
                'updated_at' => '2025-05-11 21:05:29',
            ],
            [
                'id' => 89,
                'assignment_sk' => 'Rovnica\\ 4^x-2^x=6',
                'assignment_en' => 'Equation\\ 4^x-2^x=6',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:11:44',
                'updated_at' => '2025-05-11 21:11:44',
            ],
            [
                'id' => 90,
                'assignment_sk' => 'Riešte\\ nerovnicu\\ \\frac{3x^2+8x+3}{x-1}\\ge1.\\\\ Množina\\ všetkých\\ jej\\ riešení\\ je',
                'assignment_en' => 'Solve\\ the\\ inequality\\ \\frac{3x^2+8x+3}{x-1}\\ge1.\\\\ The\\ set\\ of\\ all\\ its\\ solutions\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:15:35',
                'updated_at' => '2025-05-11 21:15:35',
            ],
            [
                'id' => 91,
                'assignment_sk' => 'Výraz\\ \\frac{1+\\sqrt{a}}{1-\\sqrt{a}}\\ :\\ \\frac{1+a}{1-a}\\ sa\\ pre\\ a\\ge0,\\ a\\ne1\\ rovná\\ výrazu',
                'assignment_en' => 'The\\ expression\\ \\frac{1+\\sqrt{a}}{1-\\sqrt{a}}\\ :\\ \\frac{1+a}{1-a}\\ for\\ a\\ge0,\\ a\\ne1\\ equals\\ the\\ expression',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:19:11',
                'updated_at' => '2025-05-11 21:19:11',
            ],
            [
                'id' => 92,
                'assignment_sk' => 'Ak\\ \\log{3} = a\\ a\\ \\log{2} = b,\\ čomu\\ sa\\ rovná\\ \\log{18}',
                'assignment_en' => 'If\\ \\log{3} = a\\ and\\ \\log{2} = b,\\ what\\ is\\ \\log{18}',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:21:51',
                'updated_at' => '2025-05-11 21:21:51',
            ],
            [
                'id' => 93,
                'assignment_sk' => 'Je\\ daná\\ lineárna\\ funkcia\\ f(x]=2x - 4.\\ Nájdite\\ jej\\ nulové\\ body.',
                'assignment_en' => 'The\\ linear\\ function\\ f(x]=2x - 4\\ is\\ given.\\ Find\\ its\\ zeros.',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:25:50',
                'updated_at' => '2025-05-11 21:25:50',
            ],
            [
                'id' => 94,
                'assignment_sk' => 'Rovnica\\ \\sqrt{-2x^2 + 2x - 3}\\ =\\ \\sqrt{-3x}\\ (v\\ \\mathbb{R}]',
                'assignment_en' => 'The\\ equation\\ \\sqrt{-2x^2 + 2x - 3}\\ =\\ \\sqrt{-3x}\\ over\\ \\mathbb{R}',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:29:16',
                'updated_at' => '2025-05-11 21:29:16',
            ],
            [
                'id' => 95,
                'assignment_sk' => 'V\\ rovine\\ ležia\\ 4\\ priamky.\\\\ Týmito\\ priamkami\\ môže\\ byť\\ rovina\\ rozdelená\\ na\\ najviac\\ n\\ častí.\\\\ Nájdite\\ n.',
                'assignment_en' => 'In\\ the\\ plane\\ there\\ are\\ 4\\ lines.\\\\ These\\ lines\\ can\\ divide\\ the\\ plane\\ into\\ at\\ most\\ n\\ regions.\\ Find\\ n.',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:31:03',
                'updated_at' => '2025-05-11 21:31:03',
            ],
            [
                'id' => 96,
                'assignment_sk' => 'Nájdite\\ počet\\ priesečníkov\\ grafu\\ funkcie\\ f(x]\\ =\\ x^2\\ -\\ 3x\\ +\\ 1\\\\ a\\ priamky\\ y\\ =\\ x\\ -\\ 4.',
                'assignment_en' => 'Find\\ the\\ number\\ of\\ intersections\\ of\\ the\\ graph\\ of\\ the\\ function\\ f(x]\\ =\\ x^2\\ -\\ 3x\\ +\\ 1\\\\ and\\ the\\ line\\ y\\ =\\ x\\ -\\ 4.',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:33:43',
                'updated_at' => '2025-05-11 21:33:43',
            ],
            [
                'id' => 97,
                'assignment_sk' => 'Spoločný\\ menovateľ\\ zlomkov\\ \\frac{x}{x+1},\\ \\frac{x}{x^2-1},\\ \\frac{x+1}{2+x}\\ je',
                'assignment_en' => 'The\\ common\\ denominator\\ of\\ the\\ fractions\\ \\frac{x}{x+1},\\ \\frac{x}{x^2-1},\\ \\frac{x+1}{2+x}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:36:49',
                'updated_at' => '2025-05-11 21:36:49',
            ],
            [
                'id' => 98,
                'assignment_sk' => 'Výrok:\\\\ "Ak\\ študent\\ maturoval\\ z\\ informatiky\\ (I],\\\\ tak\\ nematuroval\\ z\\ matematiky\\ (M]\\\\ alebo\\ nematuroval\\ z\\ fyziky\\ (F]",\\\\ je\\ ekvivalentný\\ s\\ výrokom:',
                'assignment_en' => 'The\\ statement:\\\\ "If\\ a\\ student\\ graduated\\ in\\ informatics\\ (I],\\\\ then\\ they\\ did\\ not\\ graduate\\ in\\ mathematics\\ (M]\\\\ or\\ did\\ not\\ graduate\\ in\\ physics\\ (F]",\\\\ is\\ equivalent\\ to\\ the\\ statement:',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:40:57',
                'updated_at' => '2025-05-11 21:40:57',
            ],
            [
                'id' => 99,
                'assignment_sk' => 'Každý\\ prvok\\ množiny\\ M\\ je\\ prirodzené\\ číslo,\\\\ ktoré\\ buď\\ je\\ deliteľné\\ tromi\\ a\\ nie\\ je\\ deliteľné\\ jedenástimi,\\\\ alebo\\ nie\\ je\\ deliteľné\\ tromi\\ a\\ je\\ deliteľné\\ jedenástimi.\\\\ Vyberte\\ množinu\\ s\\ touto\\ vlastnosťou.',
                'assignment_en' => 'Each\\ element\\ of\\ the\\ set\\ M\\ is\\ a\\ natural\\ number\\\\ that\\ is\\ either\\ divisible\\ by\\ 3\\ and\\ not\\ divisible\\ by\\ 11,\\\\ or\\ not\\ divisible\\ by\\ 3\\ and\\ divisible\\ by\\ 11.\\\\ Select\\ the\\ set\\ M\\ with\\ this\\ property.',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:44:57',
                'updated_at' => '2025-05-11 21:44:57',
            ],
            [
                'id' => 100,
                'assignment_sk' => 'Nájdite\\ súčet\\ prvých\\ štyroch\\ členov\\\\ a_1 + a_2 + a_3 + a_4\\\\ aritmetickej\\ postupnosti\\ \\{a_n\\}_{n=1}^\\infty,\\ ak\\ viete,\\ že\\ a_2 + a_3 = 8',
                'assignment_en' => 'Find\\ the\\ sum\\ of\\ the\\ first\\ four\\ terms\\ a_1 + a_2 + a_3 + a_4\\\\ of\\ the\\ arithmetic\\ progression\\ \\{a_n\\}_{n=1}^\\infty,\\ given\\ that\\ a_2 + a_3 = 8',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:48:32',
                'updated_at' => '2025-05-11 21:48:32',
            ],
            [
                'id' => 101,
                'assignment_sk' => 'Riešením\\ rovnice\\ \\log_{x-1}{8}\\ =\\ 3\\ je',
                'assignment_en' => 'The\\ solution\\ of\\ the\\ equation\\ \\log_{x-1}8\\ =\\ 3\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:52:48',
                'updated_at' => '2025-05-11 21:52:48',
            ],
            [
                'id' => 102,
                'assignment_sk' => 'Riešením\\ rovnice\\ \\frac{1}{5^{2x-1}}\\ =\\ 25\\ je',
                'assignment_en' => 'The\\ solution\\ of\\ the\\ equation\\ \\frac{1}{5^{2x-1}}\\ =\\ 25\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:55:15',
                'updated_at' => '2025-05-11 21:55:15',
            ],
            [
                'id' => 103,
                'assignment_sk' => 'Spoločný\\ menovateľ\\ zlomkov\\ \\frac{x}{x-2},\\ \\frac{x}{x+2},\\ \\frac{x}{4-x^2}\\ je',
                'assignment_en' => 'The\\ common\\ denominator\\ of\\ the\\ fractions\\ \\frac{x}{x-2},\\ \\frac{x}{x+2},\\ \\frac{x}{4-x^2}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 21:58:16',
                'updated_at' => '2025-05-11 21:58:16',
            ],
            [
                'id' => 104,
                'assignment_sk' => 'Kvadratický\\ trojčlen\\ 3x^2\\ +\\ 9x\\ -\\ 12\\ má\\ rozklad',
                'assignment_en' => 'The\\ quadratic\\ trinomial\\ 3x^2\\ +\\ 9x\\ -\\ 12\\ has\\ the\\ factorization',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:01:23',
                'updated_at' => '2025-05-11 22:01:23',
            ],
            [
                'id' => 105,
                'assignment_sk' => 'Riešenie\\ nerovnice\\ \\frac{1-x}{x+5}\\ge 2\\ je',
                'assignment_en' => 'The\\ solution\\ of\\ the\\ inequality\\ \\frac{1-x}{x+5}\\ge 2\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:04:52',
                'updated_at' => '2025-05-11 22:04:52',
            ],
            [
                'id' => 106,
                'assignment_sk' => 'Funkcia\\ f(x]=\\log(3 - x]\\ má\\ definičný\\ obor',
                'assignment_en' => 'The\\ function\\ f(x]=\\log(3 - x]\\ has\\ domain',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:07:37',
                'updated_at' => '2025-05-11 22:07:37',
            ],
            [
                'id' => 107,
                'assignment_sk' => 'Z\\ výroku:\\ Bod\\ A\\ nie\\ je\\ priesečníkom\\ priamok\\ p\\ a\\ q,\\ vyplýva',
                'assignment_en' => 'From\\ the\\ statement:\\ Point\\ A\\ is\\ not\\ the\\ intersection\\ of\\ lines\\ p\\ and\\ q,\\ it\\ follows',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:11:03',
                'updated_at' => '2025-05-11 22:11:03',
            ],
            [
                'id' => 108,
                'assignment_sk' => 'Riešenie\\ rovnice\\ 2^{2x+1}=4^{2x-3}\\ patrí\\ do',
                'assignment_en' => 'The\\ solution\\ of\\ the\\ equation\\ 2^{2x+1}=4^{2x-3}\\ belongs\\ to',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:14:26',
                'updated_at' => '2025-05-11 22:14:26',
            ],
            [
                'id' => 109,
                'assignment_sk' => 'Výraz\\ \\left(\\frac{1}{a}+1\\right]\\colon\\left(a+2+\\frac{1-2(a+1]^2}{a}\\right]\\ sa\\ pre\\ a\\neq 0,\\ a\\neq -1\\ rovná\\ výrazu',
                'assignment_en' => 'The\\ expression\\ \\left(\\frac{1}{a}+1\\right]\\colon\\left(a+2+\\frac{1-2(a+1]^2}{a}\\right]\\ for\\ a\\neq 0,\\ a\\neq -1\\ equals\\ the\\ expression',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:18:42',
                'updated_at' => '2025-05-11 22:18:42',
            ],
            [
                'id' => 110,
                'assignment_sk' => 'Lineárna\\ funkcia\\ f(x]=3x+1',
                'assignment_en' => 'The\\ linear\\ function\\ f(x]=3x+1',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:22:29',
                'updated_at' => '2025-05-11 22:22:29',
            ],
            [
                'id' => 111,
                'assignment_sk' => 'Rovnica\\ \\lvert x - 2\\rvert=5\\ má\\ množinu\\ riešení',
                'assignment_en' => 'The\\ equation\\ \\lvert x - 2\\rvert=5\\ has\\ the\\ set\\ of\\ solutions',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:29:01',
                'updated_at' => '2025-05-11 22:29:01',
            ],
            [
                'id' => 112,
                'assignment_sk' => 'Graf\\ funkcie\\ f(x]=3x^2-5x+2',
                'assignment_en' => 'Graph\\ of\\ the\\ function\\ f(x]=3x^2-5x+2',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:32:23',
                'updated_at' => '2025-05-11 22:32:23',
            ],
            [
                'id' => 113,
                'assignment_sk' => 'Koľkými\\ spôsobmi\\ sa\\ dá\\ rozdeliť\\ pravidelný\\ šesťuholník\\ ABCDEF\\\\ na\\ štyri\\ neprekrývajúce\\ sa\\ trojuholníky',
                'assignment_en' => 'In\\ how\\ many\\ ways\\ can\\ a\\ regular\\ hexagon\\ ABCDEF\\\\ be\\ divided\\ into\\ four\\ non-overlapping\\ triangles',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:37:52',
                'updated_at' => '2025-05-11 22:37:52',
            ],
            [
                'id' => 114,
                'assignment_sk' => 'Množina\\ riešení\\ rovnice\\ 2\\sin{x}=\\tan{x}\\ je',
                'assignment_en' => 'The\\ set\\ of\\ solutions\\ of\\ the\\ equation\\ 2\\sin{x}=\\tan{x}\\ is',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:42:15',
                'updated_at' => '2025-05-11 22:42:15',
            ],
            [
                'id' => 115,
                'assignment_sk' => 'V\\ rovine\\ ležia\\ dva\\ trojuholníky.\\ Ich\\ prienik\\ je\\ úsečka.\\ Ich\\ zjednotením\\ je:',
                'assignment_en' => 'In\\ the\\ plane\\ lie\\ two\\ triangles.\\ Their\\ intersection\\ is\\ a\\ line\\ segment.\\ Their\\ union\\ is:',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-11 22:46:12',
                'updated_at' => '2025-05-11 22:46:12',
            ],
            [
                'id' => 116,
                'assignment_sk' => 'V\\ kocke\\ so\\ stranou\\ o\\ dĺžke\\ a\\ je\\ vpísaná\\ guľa.\\\\ Vyjadrite\\ koľko\\ percent\\ objemu\\ kocky\\ tvorí\\ guľa,\\ ktorá\\ je\\ do\\ kocky\\ vpísaná.',
                'assignment_en' => 'In\\ a\\ cube\\ with\\ side\\ length\\ a,\\ a\\ sphere\\ is\\ inscribed.\\\\ Express\\ what\\ percentage\\ of\\ the\\ cube’s\\ volume\\ is\\ occupied\\ by\\ the\\ inscribed\\ sphere.',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:08:16',
                'updated_at' => '2025-05-12 00:08:16',
            ],
            [
                'id' => 117,
                'assignment_sk' => 'V\\ kocke\\ so\\ stranou\\ o\\ dĺžke\\ a\\ je\\ vpísaná\\ guľa.\\\\ O\\ koľko\\ percent\\ sa\\ zmení\\ tento\\ pomer\\ ak\\\\ stranu\\ kocky\\ zväčšíme\\ dvojnásobne\\\\ a\\ aj\\ guľu\\ zväčšíme\\ tak\\ aby\\ bola\\ stále\\ vpísaná',
                'assignment_en' => 'In\\ a\\ cube\\ with\\ side\\ length\\ a,\\ a\\ sphere\\ is\\ inscribed.\\\\ By\\ what\\ percentage\\ does\\ this\\ ratio\\ change\\\\ if\\ we\\ double\\ the\\ cube’s\\ side\\ length\\\\ and\\ also\\ enlarge\\ the\\ sphere\\ so\\ that\\ it\\ remains\\ inscribed',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:11:51',
                'updated_at' => '2025-05-12 00:11:51',
            ],
            [
                'id' => 118,
                'assignment_sk' => 'Zjednodušte\\ výraz\\ a\\ určite\\ podmienky\\ riešenia.\\\\ (\\frac{2k-1}{k+1}-\\frac{2k+1}{k-1}]:(1+\\frac{1}{k-1}]',
                'assignment_en' => 'Simplify\\ the\\ expression\\ and\\ determine\\ the\\ conditions\\ for\\ its\\ solution\\\\ (\\frac{2k-1}{k+1}-\\frac{2k+1}{k-1}]:(1+\\frac{1}{k-1}]',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:18:09',
                'updated_at' => '2025-05-12 00:18:09',
            ],
            [
                'id' => 119,
                'assignment_sk' => 'V\\ množine\\ prirodzených\\ čísel\\ \\mathbb{N}\\ riešte\\ nerovnicu:\\\\ \\frac{2x-1}{5}-\\frac{3-2x}{4}\\lt 3-\\frac{x-1}{2}',
                'assignment_en' => 'In\\ the\\ set\\ of\\ natural\\ numbers\\ \\mathbb{N},\\ solve\\ the\\ inequality:\\\\  \\frac{2x-1}{5}-\\frac{3-2x}{4}\\lt 3-\\frac{x-1}{2}',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:23:08',
                'updated_at' => '2025-05-12 00:23:08',
            ],
            [
                'id' => 120,
                'assignment_sk' => 'Vypočítajte\\ povrch\\ kocky\\ ak\\ viete,\\\\ že\\ veľkosť\\ jej\\ telesovej\\ uhlopriečky\\ je\\ u_3\\ =\\ 12\\ cm.',
                'assignment_en' => 'Calculate\\ the\\ surface\\ area\\ of\\ a\\ cube\\\\ if\\ you\\ know\\ that\\ the\\ length\\ of\\ its\\ space\\ diagonal\\ is\\ u_3\\ =\\ 12\\ cm.',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:25:31',
                'updated_at' => '2025-05-12 00:25:31',
            ],
            [
                'id' => 121,
                'assignment_sk' => 'Vypočítajte\\ rovnicu\\ 3x^2 + 5x - 2\\ =\\ 0',
                'assignment_en' => 'Solve\\ the\\ equation\\ 3x^2 + 5x - 2\\ =\\ 0',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:28:12',
                'updated_at' => '2025-05-12 00:28:12',
            ],
            [
                'id' => 122,
                'assignment_sk' => 'Pani\\ Eva\\ má\\ obdĺžnikovú\\ záhradu,\\ ktorej\\ dĺžka\\ je\\ o\\ 5\\ metrov\\ väčšia\\ ako\\ šírka.\\\\ce\\ okolo\\ záhrady\\ urobiť\\ chodník\\ široký\\ 1\\ meter.\\\\  Plocha\\ záhrady\\ je\\ 150\\ metrov\\ štvorcových.\\\\ Vypočítajte\\ rozmery\\ záhrady\\ (dĺžku\\ a\\ šírku].',
                'assignment_en' => 'Mrs.\\ Eva\\ has\\ a\\ rectangular\\ garden\\ whose\\ length\\ is\\ 5\\ meters\\ greater\\ than\\ its\\ width.\\\\ The\\ area\\ of\\ the\\ garden\\ is\\ 150\\ square\\ meters.\\\\ Mrs.\\ Eva\\ wants\\ to\\ build\\ a\\ 1\\ meter-wide\\ path\\ around\\ the\\ garden.\\\\ Calculate\\ the\\ dimensions\\ of\\ the\\ garden\\ (length\\ and\\ width].',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:33:14',
                'updated_at' => '2025-05-12 00:33:14',
            ],
            [
                'id' => 123,
                'assignment_sk' => 'Pani\\ Eva\\ má\\ obdĺžnikovú\\ záhradu,\\\\ ktorej\\ dĺžka\\ je\\ o\\ 5\\ metrov\\ väčšia\\ ako\\ šírka.\\\\ Plocha\\ záhrady\\ je\\ 150\\ metrov\\ štvorcových.\\\\ Pani\\ Eva\\ chce\\ okolo\\ záhrady\\ urobiť\\ chodník\\ široký\\ 1\\ meter.\\\\ Vypočítajte,\\ koľko\\ metrov\\ štvorcových\\ bude\\ mať\\ chodník.',
                'assignment_en' => 'Mrs.\\ Eva\\ has\\ a\\ rectangular\\ garden\\\\ whose\\ length\\ is\\ 5\\ meters\\ greater\\ than\\ its\\ width.\\\\ The\\ area\\ of\\ the\\ garden\\ is\\ 150\\ square\\ meters.\\\\ Mrs.\\ Eva\\ wants\\ to\\ build\\ a\\ 1\\ meter-wide\\ path\\ around\\ the\\ garden.\\\\ Calculate,\\ how\\ many\\ square\\ meters\\ the\\ path\\ will\\ cover.',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:35:51',
                'updated_at' => '2025-05-12 00:35:51',
            ],
            [
                'id' => 124,
                'assignment_sk' => 'Riešte\\ rovnicu:\\ \\sin(x]\\ +\\ \\cos(x]\\ =\\ 1',
                'assignment_en' => 'Solve\\ the\\ equation:\\ \\sin(x]\\ +\\ \\cos(x]\\ =\\ 1',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:39:31',
                'updated_at' => '2025-05-12 00:39:31',
            ],
            [
                'id' => 125,
                'assignment_sk' => 'Graf\\ funkcie\\\\ f:\\ y=x^2+2x-3\\\\ má\\ dva\\ priesečníky\\ s\\ osou\\ x.\\ Určte\\ vzdialenosť\\ týchto\\ priesečníkov.',
                'assignment_en' => 'The\\ graph\\ of\\ the\\ function\\\\ f:\\ y=x^2+2x-3\\\\ has\\ two\\ intersections\\ with\\ the\\ x-axis.\\ Determine\\ the\\ distance\\ between\\ these\\ intersections.',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:40:34',
                'updated_at' => '2025-05-12 00:40:34',
            ],
            [
                'id' => 126,
                'assignment_sk' => 'Určte\\ pravdivostnú\\ hodnotu\\ výrokov\\ V1\\ až\\ V5:\\\\  V1:\\ Existuje\\ prvočíslo\\ deliteľné\\ ôsmimi.\\\\  V2:\\ Všetky\\ prvočísla\\ sú\\ nepárne.\\\\  V3:\\ Existuje\\ celé\\ číslo,\\ ktoré\\ nie\\ je\\ racionálne.\\\\ V4:\\ Existuje\\ iracionálne\\ číslo,\\ ktoré\\ možno\\ zapísať\\ ako\\ podiel\\ dvoch\\ prirodzených\\ čísel.\\\\  V5:\\ Každé\\ nepárne\\ číslo\\ možno\\ zapísať\\ v\\ tvare\\ 2x+1,\\ kde\\ x\\ je\\ celé\\ číslo.\\\\  Koľko\\ výrokov\\ je\\ pravdivých?',
                'assignment_en' => 'Determine\\ the\\ truth\\ values\\ of\\ statements\\ V1\\ through\\ V5:\\\\  V1:\\ There\\ exists\\ a\\ prime\\ number\\ divisible\\ by\\ eight.\\\\  V2:\\ All\\ prime\\ numbers\\ are\\ odd.\\\\  V3:\\ There\\ exists\\ an\\ integer\\ that\\ is\\ not\\ rational.\\\\ V4:\\ There\\ exists\\ an\\ irrational\\ number\\ that\\ can\\ be\\ expressed\\ as\\ the\\ ratio\\ of\\ two\\ natural\\ numbers.\\\\ V5:\\ Every\\ odd\\ number\\ can\\ be\\ written\\ in\\ the\\ form\\ 2x+1,\\ where\\ x\\ is\\ an\\ integer.\\\\  How\\ many\\ of\\ these\\ statements\\ are\\ true?',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:44:39',
                'updated_at' => '2025-05-12 00:44:39',
            ],
            [
                'id' => 127,
                'assignment_sk' => 'Ako\\ budúci\\ možný\\ odborník\\ na\\ rádiolokáciu\\ máte\\ odhaliť\\ zdroj\\ signálu.\\\\ Máte\\ k\\ dispozícií\\ dva\\ detektory.\\\\ Prvý\\ vám\\ určuje\\ vzdialenosť\\ od\\ zdroja\\ signálu,\\ ktorá\\ je\\\\ a\\ =\\ \\sqrt{7}\\ km.\\ Druhý\\ detektor\\ je\\ c\\ =\\ 1\\ km\\\\ od\\ prvého\\ detektora\\ a\\ zistili\\ ste,\\ že\\ signál\\ prichádza\\ pod\\ uhlom\\ \\alpha\\ =\\ 60^\\circ\\\\ voči\\ pozícii\\ 1.\\ detektora.\\\\ Aplikovaním\\ kosínusovej\\ vety\\ nájdite\\ vzdialenosť\\ zdroja\\ signálu\\ od\\ 2.\\ detektora',
                'assignment_en' => 'As\\ a\\ prospective\\ radar\\ specialist,\\ you\\ must\\ locate\\ the\\ signal\\ source.\\\\ You\\ have\\ two\\ detectors.\\ The\\ first\\ measures\\ the\\ distance\\ to\\ the\\ signal\\ source,\\\\ which\\ is\\ a\\ =\\ \\sqrt{7}\\ km.\\ The\\ second\\ detector\\ is\\ c\\ =\\ 1\\ km\\\\ from\\ the\\ first\\ detector,\\ and\\ you\\ have\\ determined\\ that\\ the\\ signal\\ arrives\\ at\\\\ an\\ angle\\ \\alpha\\ =\\ 60^\\circ\\\\ relative\\ to\\ the\\ position\\ of\\ the\\ first\\ detector.\\\\ By\\ applying\\ the\\ law\\ of\\ cosines,\\\\ find\\ the\\ distance\\ from\\ the\\ signal\\ source\\ to\\ the\\ second\\ detector.',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:47:44',
                'updated_at' => '2025-05-12 00:47:44',
            ],
            [
                'id' => 128,
                'assignment_sk' => 'Máte\\ otestovaných\\ 15\\ vzoriek\\ tranzistorov,\\ kde\\ priemerný\\ odpor\\ týchto\\ vzoriek\\ je\\ 172\\ mΩ.\\\\   Vedúci\\ vám\\ prinesie\\ ďalšie\\ vzorky,\\\\ ktorých\\ odpor\\ je\\ 148\\ mΩ,\\ 152\\ mΩ,\\ 150\\ mΩ,\\ 151\\ mΩ\\ a\\ 159\\ mΩ.\\\\   Určte\\ priemerný\\ odpor\\ testovaných\\ tranzistorov.\\\\',
                'assignment_en' => 'You\\ have\\ tested\\ 15\\ transistor\\ samples,\\ with\\ an\\ average\\ resistance\\ of\\ 172\\ mΩ.\\\\   The\\ supervisor\\ will\\ bring\\ additional\\ samples\\ with\\ resistances\\ of\\\\ 148\\ mΩ,\\ 152\\ mΩ,\\ 150\\ mΩ,\\ 151\\ mΩ,\\ and\\ 159\\ mΩ.\\\\   Determine\\ the\\ average\\ resistance\\ of\\ the\\ tested\\ transistors.\\\\',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:49:58',
                'updated_at' => '2025-05-12 00:49:58',
            ],
            [
                'id' => 129,
                'assignment_sk' => 'Vypočítajte\\ medznú\\ frekvenciu\\ filtra\\ danú\\ výrazom\\ f_c=\\frac{1}{2\\pi RC}.\\ \\\\ Ak\\ R=10^4\\ \\Omega,\\ C=10^{-7}F,\\ a\\ výraz\\ \\frac{1}{2\\pi}=0.16.',
                'assignment_en' => 'Calculate\\ the\\ cutoff\\ frequency\\ of\\ the\\ filter\\ given\\ by\\ f_c=\\frac{1}{2\\pi RC}.\\ \\\\ Where\\ R=10^4\\ \\Omega,\\ C=10^{-7}F,\\ and\\ \\frac{1}{2\\pi}=0.16.',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:52:25',
                'updated_at' => '2025-05-12 00:52:25',
            ],
            [
                'id' => 130,
                'assignment_sk' => 'Vypočítajte\\ výstupné\\ napätie\\ U_{out}\\ zosilňovača\\ ak\\ vstupné\\ napätie\\ U_{in}\\ =\\ 1\\ mV.\\ \\\\   A\\ zosilnenie\\ je\\ dané\\ výrazom\\ 60\\ =\\ 20\\log\\frac{U_{out}}{U_{in}}.',
                'assignment_en' => 'Calculate\\ the\\ output\\ voltage\\ U_{out}\\ of\\ the\\ amplifier\\ if\\ the\\ input\\ voltage\\ U_{in}\\ =\\ 1\\ mV.\\ \\\\   And\\ the\\ gain\\ is\\ given\\ by\\ the\\ expression\\ 60\\ =\\ 20\\log\\frac{U_{out}}{U_{in}}.',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:54:56',
                'updated_at' => '2025-05-12 00:54:56',
            ],
            [
                'id' => 131,
                'assignment_sk' => 'Zjednodušte\\ výraz\\ \\log_2(8x^3]\\ -\\ \\log_2(x]\\ +\\ 2\\log_2(4]',
                'assignment_en' => 'Simplify\\ the\\ expression\\ \\log_2(8x^3]\\ -\\ \\log_2(x]\\ +\\ 2\\log_2(4]',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:56:52',
                'updated_at' => '2025-05-12 00:56:52',
            ],
            [
                'id' => 132,
                'assignment_sk' => '5\\ spolužiakov\\ Adam,\\ Betka,\\ Cyril,\\ Dávid\\ a\\ Evka\\ ide\\ do\\ kina,\\\\ koľkými\\ spôsobmi\\ si\\ môžu\\ sadnúť,\\\\ ak\\ Betka\\ nechce\\ sedieť\\ vedľa\\ Cyrila\\ a\\ Evka\\ chce\\ sedieť\\ na\\ kraji?\\\\',
                'assignment_en' => 'Five\\ classmates\\ Adam,\\ Betka,\\ Cyril,\\ Dávid\\ and\\ Evka\\ go\\ to\\ the\\ cinema,\\\\ in\\ how\\ many\\ ways\\ can\\ they\\ sit,\\\\ if\\ Betka\\ does\\ not\\ want\\ to\\ sit\\ next\\ to\\ Cyril\\ and\\ Evka\\ wants\\ to\\ sit\\ at\\ an\\ end?\\\\',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 00:58:48',
                'updated_at' => '2025-05-12 00:58:48',
            ],
            [
                'id' => 133,
                'assignment_sk' => 'Číslo\\ 260\\ je\\ súčtom\\ piatich\\ po\\ sebe\\ idúcich\\ čísel.\\\\ Nájdi\\ a\\ napíš\\ týchto\\ päť\\ čísel.',
                'assignment_en' => 'The\\ number\\ 260\\ is\\ the\\ sum\\ of\\ five\\ consecutive\\ numbers.\\\\ Find\\ and\\ write\\ those\\ five\\ numbers.',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 01:01:42',
                'updated_at' => '2025-05-12 01:01:42',
            ],
            [
                'id' => 134,
                'assignment_sk' => 'V\\ ktorej\\ možnosti\\ je\\ parametrická\\ rovnica\\ priamky,\\\\ ktorá\\ prechádza\\ bodmi\\ A\\ [-1;2]\\ a\\ B\\ [2;3]',
                'assignment_en' => 'Which\\ option\\ gives\\ the\\ parametric\\ equation\\ of\\ the\\ line\\\\ passing\\ through\\ points\\ A\\ [-1;2]\\ and\\ B\\ [2;3]',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-12 01:07:39',
                'updated_at' => '2025-05-12 01:07:39',
            ],
            [
                'id' => 135,
                'assignment_sk' => 'Kvadratická\\ rovnica\\ 2x^2\\ +\\ 7x\\ -\\ 4\\ =\\ 0\\ má:\\\\',
                'assignment_en' => 'The\\ quadratic\\ equation\\ 2x^2\\ +\\ 7x\\ -\\ 4\\ =\\ 0\\ has:\\\\',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-12 01:10:50',
                'updated_at' => '2025-05-12 01:10:50',
            ],
            [
                'id' => 136,
                'assignment_sk' => 'Súčet\\ 17\\ rôznych\\ prirodzených\\ čísel\\ je\\ 154.\\\\ Určte\\ súčet\\ dvoch\\ najväčších\\ z\\ nich.\\\\',
                'assignment_en' => 'The\\ sum\\ of\\ 17\\ distinct\\ natural\\ numbers\\ is\\ 154.\\\\ Determine\\ the\\ sum\\ of\\ the\\ two\\ largest\\ of\\ them.\\\\',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 01:15:10',
                'updated_at' => '2025-05-12 01:15:10',
            ],
            [
                'id' => 137,
                'assignment_sk' => 'Peter\\ každý\\ deň\\ trénuje\\ na\\ polmaratón.\\\\ Prvý\\ deň\\ prebehol\\ 1000\\ m\\ a\\ každý\\ ďalší\\ deň\\ zvyšoval\\ dĺžku\\ tréningu\\ o\\ 250\\ m.\\\\ V\\ určitý\\ deň\\ Peter\\ zabehol\\ na\\ tréningu\\ 21\\ km.\\ V\\ ten\\ deň\\ si\\ spočítal\\ celkovú\\ dráhu,\\\\ ktorú\\ zabehol\\ od\\ začiatku\\ trénovania.\\ Koľko\\ kilometrov\\ Peter\\ spolu\\ zabehol?\\\\',
                'assignment_en' => 'Peter\\ trains\\ every\\ day\\ for\\ a\\ half-marathon.\\\\ On\\ the\\ first\\ day\\ he\\ ran\\ 1000\\ m,\\ and\\ each\\ following\\ day\\\\ he\\ increased\\ his\\ training\\ distance\\ by\\ 250\\ m.\\ On\\ a\\ certain\\ day,\\\\ Peter\\ ran\\ 21\\ km\\ in\\ training.\\\\ That\\ day,\\ he\\ calculated\\ the\\ total\\ distance\\ he\\ had\\ run\\ since\\ beginning\\ his\\ training.\\\\ How\\ many\\ kilometers\\ has\\ Peter\\ run\\ in\\ total?\\\\',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 01:17:36',
                'updated_at' => '2025-05-12 01:17:36',
            ],
            [
                'id' => 138,
                'assignment_sk' => 'Ktorá\\ z\\ možností\\ je\\ zápisom\\ nasledujúceho\\ tvrdenia?\\ \\\\ Vzdialenosť\\ čísla\\ x\\ od\\ čísla\\ -4\\ na\\ číselnej\\ osi\\ je\\ 5.\\\\',
                'assignment_en' => 'Which\\ of\\ the\\ options\\ is\\ the\\ notation\\ of\\ the\\ following\\ statement?\\ \\\\ The\\ distance\\ of\\ the\\ number\\ x\\ from\\ -4\\ on\\ the\\ number\\ line\\ is\\ 5.\\\\',
                'isMultiChoice' => 1,
                'created_at' => '2025-05-12 01:21:14',
                'updated_at' => '2025-05-12 01:21:14',
            ],
            [
                'id' => 139,
                'assignment_sk' => 'Zvuk\\ prekoná\\ približne\\ 1\\ km\\ za\\ 3\\ sekundy.\\ \\\\   Hrmenie\\ bolo\\ počuť\\ 11\\ sekúnd\\ po\\ zablysnutí.\\ \\\\   V\\ akej\\ vzdialenosti\\ je\\ búrka?\\ \\\\',
                'assignment_en' => 'Sound\\ travels\\ approximately\\ 1\\ km\\ in\\ 3\\ seconds.\\ \\\\   Thunder\\ was\\ heard\\ 11\\ seconds\\ after\\ the\\ lightning.\\ \\\\   How\\ far\\ away\\ is\\ the\\ storm?\\ \\\\',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 01:22:26',
                'updated_at' => '2025-05-12 01:22:26',
            ],
            [
                'id' => 140,
                'assignment_sk' => '3D\\ tlačiareň\\ s\\ veľkosťou\\ tlačového\\ priestoru\\ XXL\\ stojí\\ 2200\\ €.\\ \\\\   Po\\ zásadnej\\ technickej\\ inovácii\\ bola\\ zdražená\\ o\\ 50\\%.\\ \\\\   Následne\\ bola\\ ponúkaná\\ v\\ akcii\\ zlacnená\\ o\\ 10\\%.\\ \\\\   Aká\\ bola\\ jej\\ konečná\\ cena,\\ ak\\ kupujúci\\ mal\\ k\\ dispozícii\\\\ bonusovú\\ kartu\\ na\\ extra\\ 10\\%\\ zľavu\\ na\\ nákup?\\',
                'assignment_en' => 'A\\ 3D\\ printer\\ with\\ an\\ XXL\\ build\\ volume\\ costs\\ €2200.\\ \\\\   After\\ a\\ major\\ technical\\ upgrade,\\ its\\ price\\ increased\\ by\\ 50\\%.\\ \\\\   It\\ was\\ then\\ offered\\ on\\ sale\\ with\\ a\\ 10\\%\\ discount.\\ \\\\   What\\ was\\ its\\ final\\ price\\ if\\ the\\ buyer\\ also\\ had\\\\ a\\ bonus\\ card\\ for\\ an\\ extra\\ 10\\%\\ off\\ the\\ purchase?\\',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 01:23:23',
                'updated_at' => '2025-05-12 01:23:23',
            ],
            [
                'id' => 141,
                'assignment_sk' => 'V\\ zásuvke\\ sú\\ elektronické\\ súčiastky.\\\\ Diódy\\ majú\\ dve\\ elektródy\\ a\\ tranzistory\\ majú\\ tri\\ elektródy.\\ \\\\ Spolu\\ máme\\ 22\\ súčiastok,\\ ktoré\\ majú\\ spolu\\ 54\\ elektród.\\\\ Koľko\\ máme\\ diód\\ a\\ koľko\\ tranzistorov',
                'assignment_en' => 'In\\ the\\ drawer\\ there\\ are\\ electronic\\ components.\\\\ Diodes\\ have\\ two\\ electrodes\\ and\\ transistors\\ have\\ three\\ electrodes.\\ \\\\ Altogether,\\ there\\ are\\ 22\\ components\\ with\\ a\\ total\\ of\\ 54\\ electrodes.\\\\ How\\ many\\ diodes\\ and\\ how\\ many\\ transistors\\ are\\ there',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 01:25:14',
                'updated_at' => '2025-05-12 01:25:14',
            ],
            [
                'id' => 142,
                'assignment_sk' => 'Obsah\\ medzikružia\\ tvorený\\ dvoma\\ kružnicami\\ so\\ spoločným\\ stredom\\ je\\ 100\\ cm^2.\\ \\\\   Polomer\\ vonkajšej\\ kružnice\\ sa\\ rovná\\ dvojnásobku\\ polomeru\\ vnútornnej\\ kružnice.\\ \\\\   Určte\\ v\\ centimetroch\\ veľkosť\\ polomeru\\ vonkajšej\\ kružnice.\\',
                'assignment_en' => 'The\\ area\\ of\\ the\\ annulus\\ formed\\ by\\ two\\ concentric\\ circles\\ is\\ 100\\ cm^2.\\ \\\\   The\\ radius\\ of\\ the\\ outer\\ circle\\ is\\ twice\\ that\\ of\\ the\\ inner\\ circle.\\ \\\\   Determine\\ the\\ radius\\ of\\ the\\ outer\\ circle\\ in\\ centimeters.\\',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 01:26:54',
                'updated_at' => '2025-05-12 01:26:54',
            ],
            [
                'id' => 143,
                'assignment_sk' => 'Do\\ akej\\ výšky\\ siaha\\ hladina\\ vody\\ v\\ akváriu,\\\\ ktoré\\ má\\ rozmery\\ podstavy\\ 50\\ cm\\ a\\ 20\\ cm,\\ keď\\ je\\ v\\ ňom\\ 100\\ litrov\\ vody?\\ \\\\',
                'assignment_en' => 'Up\\ to\\ what\\ height\\ does\\ the\\ water\\ level\\ reach\\ in\\ an\\ aquarium\\\\ with\\ a\\ base\\ measuring\\ 50\\ cm\\ by\\ 20\\ cm,\\ when\\ it\\ contains\\ 100\\ liters\\ of\\ water?\\ \\\\',
                'isMultiChoice' => 0,
                'created_at' => '2025-05-12 01:28:05',
                'updated_at' => '2025-05-12 01:28:05',
            ]
        ];
        
        DB::table("questions")->insert($dataTables);
    }
}